{% set name = "PyInstaller" %}
# NOTE: the test step triggers antivirus stuff.  Let IT know that you're building a new pyinstaller release,
#    and that they should watch for hello.exe triggering alerts.  Windows jobs in particular will fail with
#    what looks like a permission error.
{% set version = "5.6.2" %}
{% set sha256 = "865025b6809d777bb0f66d8f8ab50cc97dc3dbe0ff09a1ef1f2fd646432714fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - pyinstaller = PyInstaller.__main__:run
    - pyi-archive_viewer = PyInstaller.utils.cliutils.archive_viewer:run
    - pyi-bindepend = PyInstaller.utils.cliutils.bindepend:run
    - pyi-grab_version = PyInstaller.utils.cliutils.grab_version:run
    - pyi-makespec = PyInstaller.utils.cliutils.makespec:run
    - pyi-set_version = PyInstaller.utils.cliutils.set_version:run
  script:
    - export PYI_STATIC_ZLIB=1  # [unix]
    - export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"               # [unix]
    # Remove the pre-compiled bootloaders (available in sdist)
    - rm -fr ${SRC_DIR}/PyInstaller/bootloader/{Darwin,Linux,Windows}-{64,32}bit  # [unix]
    # Remove vendored waflib dir
    - rm -fr ${SRC_DIR}/bootloader/waflib   # [unix]
    - rd /s /q %SRC_DIR%\bootloader\waflib  # [win]
    # Build the bootloader
    - pushd bootloader
    - waf --prefix="${PREFIX}" --target-arch=64bit --clang distclean all  # [osx]
    - waf --prefix="${PREFIX}" --gcc --no-lsb distclean all     # [linux]
    - waf --prefix="%LIBRARY_PREFIX%" distclean all             # [win]
    - popd
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  preserve_egg_dir: True

requirements:
  build:
    - {{ compiler("c") }}
    - pip
    - python
    - setuptools
    - m2-patch  # [win]
    - patch  # [not win]

  host:
    - pip
    - python
    - setuptools
    - wheel
    - waf
    - zlib

  run:
    - altgraph
    - python
    - pefile >=2022.5.30  # [win]
    - pywin32  # [win]
    - pywin32-ctypes  # [win]
    - macholib >=1.8
    - setuptools    # due to pkg_resources import
    - importlib-metadata >=0.8  # [py<38]

test:
  imports:
    - PyInstaller
  commands:
    - pyinstaller --help
    - pyi-archive_viewer --help
    - pyi-bindepend --help
    - pyi-makespec --help
    # These are designed for Windows only.
    - pyi-grab_version --help     # [win]
    - pyi-set_version --help      # [win]
  files:
    - hello.py
    - multiprocessing_test.py

about:
  home: http://www.pyinstaller.org
  # https://github.com/pyinstaller/pyinstaller/blob/v3.6/COPYING.txt#L11
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.txt
  summary: PyInstaller bundles a Python application and all its dependencies into a single package.

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - hadim
    - nehaljwani
    - mingwandroid
