{% set name = "pyinstaller" %}
{% set version = "6.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f4b6520f4423fe19bcc2fd63ab7238851ae2bdcbc98f25bc5d2f97cc62012e9

build:
  number: 0
  skip: True  # [py<38 and py>313]
  entry_points:
    - pyinstaller = PyInstaller.__main__:run
    - pyi-archive_viewer = PyInstaller.utils.cliutils.archive_viewer:run
    - pyi-bindepend = PyInstaller.utils.cliutils.bindepend:run
    - pyi-grab_version = PyInstaller.utils.cliutils.grab_version:run
    - pyi-makespec = PyInstaller.utils.cliutils.makespec:run
    - pyi-set_version = PyInstaller.utils.cliutils.set_version:run
  script:
    - export PYI_STATIC_ZLIB=1  # [unix]
    - export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"               # [unix]
    # Remove the pre-compiled bootloaders (available in sdist)
    - rm -fr ${SRC_DIR}/PyInstaller/bootloader/{Darwin,Linux,Windows}-{64,32}bit  # [unix]
    # Remove vendored waflib dir
    - rm -fr ${SRC_DIR}/bootloader/waflib   # [unix]
    - rd /s /q %SRC_DIR%\bootloader\waflib  # [win]
    # Build the bootloader
    - pushd bootloader
    - waf --prefix="${PREFIX}" --target-arch=64bit --clang distclean all  # [osx]
    - waf --prefix="${PREFIX}" --gcc --no-lsb distclean all     # [linux]
    - waf --prefix="%LIBRARY_PREFIX%" distclean all             # [win]
    - popd
    - "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
  preserve_egg_dir: True
  overlinking_ignore_patterns:   # [s390x]
    - '*'                        # [s390x]

requirements:
  build:
    - {{ compiler("c") }}

  host:
    - pip
    - python
    - setuptools
    - wheel
    - waf

  run:
    - python
    - setuptools >=42.0.0
    - altgraph
    # - binutils  # [aarch64]
    - pefile >=2022.5.30  # [win]
    - pywin32-ctypes >=0.2.1 # [win]
    - macholib >=1.8  # [osx]
    - pyinstaller-hooks-contrib >=2024.6
    # - pywin32  # [win]
    - importlib-metadata >=4.6  # [py<310]
    - packaging >=22.0

test:
  imports:
    - PyInstaller
  requires:
    - pip
  files:
    - hello.py
    - multiprocessing_test.py

about:
  home: https://pyinstaller.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.txt
  summary: PyInstaller bundles a Python application and all its dependencies into a single package.
  description: |
      PyInstaller bundles a Python application and all its dependencies into a single package.
      The user can run the packaged app without installing a Python interpreter or any modules.
      PyInstaller reads a Python script written by you. It analyzes your code to discover every
      other module and library your script needs in order to execute. Then it collects copies of
      all those files -- including the active Python interpreter! -- and puts them with your script
      in a single folder, or optionally in a single executable file.
  dev_url: https://github.com/pyinstaller/pyinstaller
  doc_url: https://pyinstaller.org

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - hadim
    - nehaljwani
    - mingwandroid
