travis:
  secure:
    BINSTAR_TOKEN: VS0FWzcfvlq8+aCIXpiAppCBJZ50rnIeLOEg0DcZ9X2z1Ayz8ZWn2poIOhwVc6dTC9PDzN4QDSIi8KswlyDXJ4Tq6Huv8Nxyq7u3Ohii5zEojfj4+5MZJ6P2O+kbG1cUJOyTY+tTfQsT4GJZx/oWMHG9ReU/ZKGWO+9cdLRwyX9hIvER2h53mm0EKy3LhXyjoRbq70zf8vngfOH16+4pfFRYD3P0sYGZPS2A0VVHIsGBl+m3JVFV6v61WkXkuLYvJs3RJyczgS+x0vPibt53yz1vRvZjfd/6dASC1PGh1XwDiRLFrlWG59x+sEbfsF5Dz+CkMXFD2ufym9yGrw/DuseYCuiE9pjbi+Tcn3SQhFbyZHGm1T3OEeyiWj+7H4V93lEBtd5cs1p/ntjtYgNtyJdCSAeB9wcN549udv9Bb8AiTS1lxOSkX2qy8qReiBtSL583uNwLUEdX92+dd1Rxklj6kUozz3/V8kRxt09oyi/+SOQyMvJUtODf4g+rrWOPhgprUtw37yR+uCb0qeEuwNXQp7SsWmGKMdqZeQVjX7q6pE1xBXDWBE06TdReuC4Q/GQ2RmHPsbhohrh+0XgwdG/bkGed9WUwOy8doTFSxJp15rG6gxgboyUweXi9JSLwumqCjFcJSXdocJG5VllNmTJQHJ/8OQ6bP07lgTGzz1A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
